# Exported from Render on 2024-09-14T09:12:21Z
services:
- type: web
  name: telethon-api-forwarder
  runtime: python
  repo: https://github.com/teegee-123/telethon-api-forwarder
  plan: free
  envVars:
  - key: SLEEP_TIME
    sync: false
  - key: SESSION
    sync: false
  - key: MAESTRO_ID
    sync: false
  - key: BUYSIGNALSGROUP
    sync: false
  - key: CODE_FILE
    sync: false
  - key: API_HASH
    sync: false
  - key: TRAILING_STOP
    sync: false
  - key: FEEDS
    sync: false
  - key: REPORT_GROUPS
    sync: false
  - key: TRADEBOTNAME
    sync: false
  - key: PHONE
    sync: false
  - key: API_ID
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
version: "1"
